### ISSUE TITLE
Extended html often unavailable on initial request

### ISSUE THREAD

**Issue by ragesoss** [wikiwho/WhoColor#15]
Lately, the [Wiki Education Dashboard implementation of authorship highlighting](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/components/common/article_viewer.jsx) that uses api.wikiwho.net extended_html data has been very unreliable, because many requests return `success: false` with a message saying the data is not available but will be soon.

I [found a workaround](https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/14c53e66e70f0f6a5ba90b5d5f5ee49f931c5939) when this happens, to request the `rev_content` endpoint for the same article, and then try again to get the extended_html, and this seems to be working pretty consistently.

If this is a bad idea, or you have other suggestions for making the fetching of extended_html more reliable, please let me know.

:-)

**Comment by faflo** [comment]
Thanks, that seems to be a problem with our task-queue being filled from WM's EventStream. Keep doing your workaround for now, I will look into it.

**Comment by robertour** [comment]
Thanks @ragesoss,

I traced back the problem:

Our queue system was partially down. Some queues  were not being processed. I restarted and everything seems to be back to normal, except that the server will need a couple of days to consume the rest of the articles that haven't been updated. 

Although the above will solve your problem for most of your cases, there is still a small window in which you could get the same error. If the article is not updated in our server, then the `extended_html`  endpoint sends the process to a queue (this queue was being ignored), and **immediately** reports that the article is not ready; after a few seconds (or sometimes minutes or hours depending  on the article) the article should be processed, so the second query will work. Instead, the `rev_content` will wait five minutes (enough for most of the articles) before return a failure message.

We will decide if we should change the behavior so that the `extended_html` also waits 5 minutes, before sending a failure.
