### ISSUE TITLE
Doesn't work for the Italian Wikipedia

### ISSUE THREAD

**Issue by koba-1** [wikiwho/WhoColor#23]
I don't know if it's normal that it doesn't work. The "WhoColor" tab appears on the left of the articles, but when clicked, it loads indefinitely. Try it here at this link, for example: https://it.wikipedia.org/wiki/Palermo

**Comment by ragesoss** [comment]
@koba-1 Italian isn't one of the supported languages. It's only available for 5 languages so far, as listed here: https://api.wikiwho.net/

**Comment by koba-1** [comment]
I'm so sorry. The Italian Wikipedia is the [fifth largest](https://www.wikipedia.org/)... it could be used by many users. Wouldn't it be possible to implement it also for Italian? Can I help in any way?

**Comment by ragesoss** [comment]
This is a side project for its maintainer @faflo, but I'm not sure exactly what it would take to add support for more languages. It might require someone else taking on responsibility for creating and maintaining the infrastructure, for example by setting it up on `wmcloud.org`. I think the Wikimedia Community Tech team considered this when they were working on the "who wrote that" extension, but determined it was too big a project for them to take on indefinitely. Perhaps @Niharika29 or @musikanimal know more.

**Comment by faflo** [comment]
Thanks @ragesoss for the explanation. Exactly, I/we will not be able to expand to any other languages with the current setup. The process is not that complicated, but requires to run the WikiWho algorithm over the whole revision dump of the respective language edition, and then setup the listener/collector for the event stream. For Romance languages I don't see a a huge risk of WikiWho being more imprecise either (so not even tokenization has to be adapted probably). 
So yes, the only way to do this (and the best one, since I'm not sure how long WikiWho.net can be maintained at the current server in the coming years) would be to set it up somewhere with a broader community backing, like wmcloud.org .
