### ISSUE TITLE
For some articles, token annotations stop partway through (edit: <nowiki> tag issue)

### ISSUE THREAD

**Issue by ragesoss** [wikiwho/WhoColor#9]
For example, https://api.wikiwho.net/eu/whocolor/v1.0.0-beta/Virginia%20Hendersonen%20eredua/

Article: https://eu.wikipedia.org/wiki/Virginia_Hendersonen_eredua

View it from Programs & Events Dashboard: https://outreachdashboard.wmflabs.org/courses/EHU,_EWKE_eta_Donostia_Kultura/EHU-Wikipedia_2017/articles

Here's the visualization of how far into the article the authorship tokens go: 
![partial coloring](https://user-images.githubusercontent.com/848483/31785041-bb16e808-b4b8-11e7-9010-e9c4d729bbab.png)

**Comment by faflo** [comment]
seems like the `<nowiki/>` tag is breaking the parser, we look into it

**Comment by bitnik** [comment]
problem was that parser was able to detect start of single `nowiki` tag but cannot detect end, because it was expecting it in `<nowiki> ... </nowiki>` form. so everything else after `<nowiki />` was detected as inside that tag and no spans were added. 

`<nowiki />`  is added into special markups. it should work now.

**Comment by faflo** [comment]
this seems to be resolved, at least for that instance. If another issue with that specific tag pops up please report it here as well. cheers
